version: '3'

services:
  strava_app:
    image: ghcr.io/benmepham/strava-app
    container_name: strava_app
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production # defaults to development
    ports:
      - 3000:3000
    command: ./wait-for.sh mongodb:27017 -- node ./bin/www

  mongodb:
    image: mongo:5
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASS
      - MONGO_INITDB_DATABASE=$MONGO_DB
    volumes:
      - dbdata_prod:/data/db
    command: --quiet

volumes:
  dbdata_prod:
