version: '3'

services:
  mongodb:
    image: mongo:5
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASS
      - MONGO_INITDB_DATABASE=$MONGO_DB
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
